site_name: STACK
site_url: https://stack-assessment.org/
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
    name: bootstrap
    custom_dir: theme
    logo: img/logo_large.svg
    nav_style: secondary
extra_css:
    - custom.css
docs_dir: 'website_files'
markdown_extensions:
    - mdx_math
plugins:
    - include_dir_to_nav:
        file_name_as_title: true
        recurse: true
        reverse_sort_directory: true
nav:
    - Home: 'index.md'
    - About: 'About.md'
    - Get Started: 'GetStarted.md'
    - Community:
        - 'Overview': 'Community.md'
        - 'Development team': 'Communities/Development_team.md'
        - 'International Advisory Board': 'Communities/Advisory_board.md'
        - 'African STACK Community Leadership Team': 'Communities/African_leadership.md'
        - 'STACK Professionals Network': 'Communities/Professional_network.md'
        - 'STACK Researchers Network': 'Communities/Researchers_network.md'
        - 'Commercial Partners': 'Partners/index.md'
    - Training and Events: 
        - 'Meetings': 'Training_and_events.md'
        - 'Annual conferences': 'Conference.md'
        - 'Training events in 2020': '2020meetings.md'
        - 'Meeting reports': 'MeetingReports/index.md'
    - Projects:
        - 'Overview': 'Projects/index.md'
        - 'STACKnet' : 'Projects/STACKnet/index.md'
        - 'IdeaL' : 'Projects/IDEAL/index.md'
        - 'KTP' : 'Projects/KTP/index.md'
        - 'AuthOMath': 'Projects/AuthOMath/index.md'
        - 'IDIAM': 'Projects/IDIAM/index.md'
    - Case Studies: CaseStudies/
    - Demo: 'https://stack-demo.maths.ed.ac.uk/demo/'
    - Documentation: 'https://docs.stack-assessment.org/en/'

