site_name: STACK
site_url: https://stack-assessment.org/
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
    name: bootstrap
    custom_dir: theme
    logo: img/logo_large.svg
    nav_style: secondary
extra_css:
    - custom.css
docs_dir: 'website_files'
markdown_extensions:
    - mdx_math
plugins:
    - include_dir_to_nav:
        file_name_as_title: true
        recurse: true
        reverse_sort_directory: true
nav:
    - Home: 'index.md'
    - About: 'About.md'
    - Get Started: 'GetStarted.md'
    - Community:
        - 'Overview': 'Community.md'
        - 'Development team': 'Communities/Development_team.md'
        - 'International Advisory Board': 'Communities/Advisory_board.md'
        - 'African STACK Community Leadership Team': 'Communities/African_leadership.md'
        - 'STACK-connect: the German-speaking Community': 'Communities/STACK_Connect.md'
        - 'STACK Connect: Netzwerk f√ºr die deutschsprachige STACK-Community': 'Communities/STACK_Connect_de.md'
        - 'STACK Professionals Network': 'Communities/Professional_network.md'
        - 'STACK Researchers Network': 'Communities/Researchers_network.md'
        - 'Commercial Partners': 'Partners/index.md'
    - Training and Events:
        - Meetings: Training_and_events.md
        - Seminars: Seminars.md
        - Annual conferences:
            - Overview: Conference.md
            - International Meeting of the STACK Community 2026: Events/2026-07-27-Conf-2026/index.md
        - Training events in 2020: 2020meetings.md
        - Meeting reports: MeetingReports/index.md
    - Projects:
        - 'Overview': 'Projects/index.md'
        - 'STACK.nrw': 'Projects/STACKnrw/index.md'
        - 'STACKnet' : 'Projects/STACKnet/index.md'
        - 'IdeaL' : 'Projects/IDEAL/index.md'
        - 'KTP' : 'Projects/KTP/index.md'
        - 'AuthOMath': 'Projects/AuthOMath/index.md'
        - 'IDIAM': 'Projects/IDIAM/index.md'
        - 'LLV.HD': 'Projects/LLV.HD/index.md'
    - Case Studies: CaseStudies/
    - Demo: 'https://stack-demo.maths.ed.ac.uk/demo/'
    - Documentation: 'https://docs.stack-assessment.org/en/'
extra:
  subnavs:
    conf2026:
      - title: Home
        href: /Events/2026-07-27-Conf-2026/
        children:
          - { title: Overview, href: /Events/2026-07-27-Conf-2026/ }
          - { title: Leadership & Organisers, href: /Events/2026-07-27-Conf-2026/committee/ }
          - { title: Key Dates, href: /Events/2026-07-27-Conf-2026/dates/ }
      - { title: Venue, href: /Events/2026-07-27-Conf-2026/venue/ }
      - { title: Conference Format, href: /Events/2026-07-27-Conf-2026/conference-format/ }
      - { title: Registration, href: /Events/2026-07-27-Conf-2026/registration/ }
      - { title: Abstract Submission, href: /Events/2026-07-27-Conf-2026/abstract-submission/ }
#      - { title: Conference Proceedings, href: /Events/2026-07-27-Conf-2026/conference-proceedings/ }
      - { title: Cultural Activities, href: /Events/2026-07-27-Conf-2026/cultural-activities/ }
