site_name: STACK
site_url: https://stack-assessment.org/
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
theme:
    name: bootstrap
    custom_dir: overrides
    logo: img/logo_large.svg
    nav_style: secondary
extra_css:
    - custom.css
docs_dir: 'website_files'
markdown_extensions:
    - mdx_math
nav:
    - Home: 'index.md'
    - About: 'About.md'
    - Get Started: 'GetStarted.md'
    - Community: 'Community.md'
    - Training and Events: 
        - 'Meetings': 'Training_and_events.md'
        - 'Annual conferences': 'Conference.md'
        - 'Training events in 2020': '2020meetings.md'
        - 'Meeting reports': 'MeetingReports/index.md'
    - Projects:
        - Overview: 'Projects/index.md'
    - Case Studies:
        - Overview: 'CaseStudies/index.md'
        - 2023:
            - 'CaseStudies/2023/Bahir_Dar_University_Workshop.md'
            - 'CaseStudies/2023/Partial_frac_int.md'
        - 2022:
            - 'CaseStudies/2022/StringSimilarity.md'
            - 'CaseStudies/2022/HonoursComplexVariables.md'
            - 'CaseStudies/2022/MasenoWorkshop.md'
        - 2021:
            - 'CaseStudies/2021/Warwick.md'
            - 'CaseStudies/2021/HELM.md'
        - 2020:
            - 'CaseStudies/2020/MINTFIT.md'
            - 'CaseStudies/2020/OTH.md'
        - 2019:
            - 'CaseStudies/2019/FAC.md'
            - 'CaseStudies/2019/PhysicsCurriculum.md'
            - 'CaseStudies/2019/Adaptive.md'
            - 'CaseStudies/2019/FlickInterface.md'
            - 'CaseStudies/2019/Maseno.md'
            - 'CaseStudies/2019/optes.md'
            - 'CaseStudies/2019/ILIAS.md'
            - 'CaseStudies/2019/StackAtScale.md'
            - 'CaseStudies/2019/ABACUS.md'
            - 'CaseStudies/2019/Loughborough.md'
            - 'CaseStudies/2019/Edinburgh.md'
    - Demo: 'https://stack-demo.maths.ed.ac.uk/demo/'
    - Documentation: 'https://docs.stack-assessment.org/en/'

